jobs:
  build_linux:
    name: Linux build and test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Setup Moxie
      run: 'wget http://gitblit-org.github.io/moxie/maven/com/gitblit/moxie/moxie+ant/0.10.0/moxie+ant-0.10.0.tar.gz

        tar -xzf moxie+ant-0.10.0.tar.gz

        moxie-0.10.0/bin/moxie -version

        '
    - continue-on-error: true
      name: Report Java version
      run: 'java -version

        javac -version

        '
    - continue-on-error: true
      name: Build with Moxie
      run: moxie-0.10.0/bin/moxie test
    strategy:
      matrix:
        java-version:
        - 8
        - 11
  build_windows:
    name: Windows build and test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Report Java version
      run: 'java -version

        javac -version

        '
    - continue-on-error: true
      name: Build with Ant
      run: ant test
    strategy:
      matrix:
        java-version:
        - 8
        - 11
name: Continous integration
on:
  repository_dispatch:
    types: trigger-ga___ci-build.yml
